import pg from 'pg';
const {Pool}=pg;
const pool=new Pool({connectionString:process.env.DATABASE_URL,max:3,connectionTimeoutMillis:10000,idleTimeoutMillis:30000});
const MODEL=process.env.DEEPSEEK_MODEL||'deepseek-flash';
const timeout=(ms)=>new Promise(r=>setTimeout(r,ms));
function decode(s=''){return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');}
async function text(url,ms=7000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'Mozilla/5.0 RabbitHole/2.0'}});if(!r.ok)throw new Error(`${r.status}`);return await r.text();}finally{clearTimeout(t);}}
function heuristic(title=''){
  const t=title.toLowerCase(); let score=70,type='explainer';
  if(/#shorts\b|\bshorts\b/.test(t)){score=10;type='short';}
  else if(/\b(trailer|teaser|giveaway|merch|channel update|announcement)\b/.test(t)){score=25;type='promo';}
  else if(/\b(livestream|live stream|stream highlights?)\b/.test(t)){score=35;type='livestream';}
  else if(/\b(podcast|interview|conversation)\b/.test(t)){score=64;type='interview';}
  else if(/\b(news|update|this week|today)\b/.test(t)){score=66;type='news';}
  if(/\b(how|why|explained|inside|history|science|engineering|future|economics|physics|math|system|works?)\b/.test(t))score+=8;
  if(t.length>45)score+=3;
  score=Math.max(0,Math.min(100,score));
  return {score,type,recommendable:score>=55};
}
async function setup(){await pool.query(`
CREATE TABLE IF NOT EXISTS channel_ingestion(channel_id INT PRIMARY KEY REFERENCES channels(id) ON DELETE CASCADE,youtube_channel_id TEXT,last_synced_at TIMESTAMPTZ,last_error TEXT);
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'curated';
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS youtube_video_id TEXT;
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ;
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS recommendable BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS quality_score SMALLINT NOT NULL DEFAULT 70;
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS content_type TEXT;
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS ai_summary TEXT;
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS ai_reason TEXT;
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS difficulty SMALLINT;
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS tags JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS enriched_at TIMESTAMPTZ;
CREATE UNIQUE INDEX IF NOT EXISTS learning_items_youtube_video_id_uidx ON learning_items(youtube_video_id) WHERE youtube_video_id IS NOT NULL;
DELETE FROM daily_picks WHERE item_id IS NULL;
UPDATE learning_items SET recommendable=TRUE,quality_score=100,content_type=COALESCE(content_type,'curated'),enriched_at=COALESCE(enriched_at,NOW()) WHERE source='curated';
`);}
async function resolve(c){const cached=(await pool.query('SELECT youtube_channel_id FROM channel_ingestion WHERE channel_id=$1',[c.id])).rows[0]?.youtube_channel_id;if(cached)return cached;const html=await text(c.url);const id=[/"channelId":"(UC[\w-]{20,})"/,/"externalId":"(UC[\w-]{20,})"/,/youtube\.com\/channel\/(UC[\w-]{20,})/].map(x=>html.match(x)?.[1]).find(Boolean);if(!id)throw new Error('channel id not found');await pool.query(`INSERT INTO channel_ingestion(channel_id,youtube_channel_id) VALUES($1,$2) ON CONFLICT(channel_id) DO UPDATE SET youtube_channel_id=EXCLUDED.youtube_channel_id`,[c.id,id]);return id;}
function entries(xml){return (xml.match(/<entry>[\s\S]*?<\/entry>/g)||[]).map(b=>({id:b.match(/<yt:videoId>([^<]+)<\/yt:videoId>/)?.[1],title:decode(b.match(/<title>([\s\S]*?)<\/title>/)?.[1]||'').trim(),description:decode(b.match(/<media:description>([\s\S]*?)<\/media:description>/)?.[1]||'').replace(/\s+/g,' ').trim().slice(0,1200),published:b.match(/<published>([^<]+)<\/published>/)?.[1]||null})).filter(x=>x.id&&x.title).slice(0,12);}
async function sync(c){try{const yid=await resolve(c),xml=await text(`https://www.youtube.com/feeds/videos.xml?channel_id=${yid}`),vs=entries(xml);for(const v of vs){const h=heuristic(v.title);await pool.query(`INSERT INTO learning_items(track_id,channel_id,title,url,topic,description,item_order,repeat_after_days,source,youtube_video_id,published_at,recommendable,quality_score,content_type) VALUES(NULL,$1,$2,$3,$4,$5,NULL,60,'youtube_feed',$6,$7,$8,$9,$10) ON CONFLICT(url) DO UPDATE SET title=EXCLUDED.title,topic=EXCLUDED.topic,description=CASE WHEN learning_items.source='curated' THEN learning_items.description ELSE EXCLUDED.description END,source=CASE WHEN learning_items.source='curated' THEN 'curated' ELSE 'youtube_feed' END,youtube_video_id=COALESCE(learning_items.youtube_video_id,EXCLUDED.youtube_video_id),published_at=EXCLUDED.published_at,recommendable=CASE WHEN learning_items.source='curated' THEN TRUE ELSE COALESCE(learning_items.recommendable,EXCLUDED.recommendable) END,quality_score=CASE WHEN learning_items.source='curated' THEN 100 WHEN learning_items.enriched_at IS NOT NULL THEN learning_items.quality_score ELSE EXCLUDED.quality_score END,content_type=CASE WHEN learning_items.source='curated' THEN COALESCE(learning_items.content_type,'curated') WHEN learning_items.enriched_at IS NOT NULL THEN learning_items.content_type ELSE EXCLUDED.content_type END`,[c.id,v.title,`https://www.youtube.com/watch?v=${v.id}`,c.topic,v.description||`Recent upload from ${c.name}.`,v.id,v.published,h.recommendable,h.score,h.type]);}
await pool.query(`INSERT INTO channel_ingestion(channel_id,youtube_channel_id,last_synced_at,last_error) VALUES($1,$2,NOW(),NULL) ON CONFLICT(channel_id) DO UPDATE SET youtube_channel_id=EXCLUDED.youtube_channel_id,last_synced_at=NOW(),last_error=NULL`,[c.id,yid]);return vs.length;}catch(e){console.warn(`[catalog] ${c.name}: ${e.message}`);await pool.query(`INSERT INTO channel_ingestion(channel_id,last_synced_at,last_error) VALUES($1,NOW(),$2) ON CONFLICT(channel_id) DO UPDATE SET last_synced_at=NOW(),last_error=EXCLUDED.last_error`,[c.id,String(e.message).slice(0,250)]).catch(()=>{});return 0;}}
async function catalog(){await setup();const {rows}=await pool.query(`SELECT c.id,c.name,c.url,c.topic,ci.last_synced_at FROM channels c LEFT JOIN channel_ingestion ci ON ci.channel_id=c.id ORDER BY c.sort_order`);const stale=rows.filter(x=>!x.last_synced_at||Date.now()-new Date(x.last_synced_at).getTime()>12*3600000);let total=0;for(let i=0;i<stale.length;i+=6){const n=await Promise.all(stale.slice(i,i+6).map(sync));total+=n.reduce((a,b)=>a+b,0);if(i+6<stale.length)await timeout(150);}const count=+(await pool.query('SELECT COUNT(*)::int c FROM learning_items')).rows[0].c;console.log(`[catalog] synced ${stale.length} channels / ${total} feed entries; ${count} videos available`);}
async function deepSeekBatch(videos){if(!process.env.DEEPSEEK_API_KEY||!videos.length)return null;const c=new AbortController(),timer=setTimeout(()=>c.abort(),12000);try{const r=await fetch('https://api.deepseek.com/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${process.env.DEEPSEEK_API_KEY}`},body:JSON.stringify({model:MODEL,temperature:0.1,max_tokens:2200,response_format:{type:'json_object'},messages:[{role:'system',content:`You curate a high-quality nightly learning library. Judge whether each YouTube video is genuinely worth recommending for curious adult learning. Penalize Shorts, promos, trailers, routine announcements, shallow clickbait, repetitive updates, and low-substance uploads. News/current-tech videos may still score highly when informative. Prefer explainers, documentaries, engineering breakdowns, scientific reasoning, economics, systems thinking, history, and substantial interviews. Return JSON exactly as {"videos":[{"id":"youtube id","score":0,"recommendable":true,"contentType":"explainer|documentary|news|interview|short|promo|livestream|other","difficulty":1,"summary":"one useful sentence","reason":"brief curator reason","tags":["tag"]}]}. score is 0-100; recommendable should normally require score >=55. difficulty is 1-5. Do not invent ids.`},{role:'user',content:JSON.stringify(videos)}]}),signal:c.signal});if(!r.ok)throw new Error(`DeepSeek HTTP ${r.status}`);const data=await r.json(),raw=data?.choices?.[0]?.message?.content;if(!raw)return null;return JSON.parse(raw);}catch(e){console.warn(`[enrich] ${e.message}`);return null;}finally{clearTimeout(timer);}}
function normalizeAi(x){const score=Math.max(0,Math.min(100,Number(x?.score)||0));const difficulty=Math.max(1,Math.min(5,Number(x?.difficulty)||2));const tags=Array.isArray(x?.tags)?x.tags.filter(t=>typeof t==='string').slice(0,8):[];return {score,difficulty,tags,recommendable:Boolean(x?.recommendable)&&score>=55,type:String(x?.contentType||'other').slice(0,40),summary:String(x?.summary||'').replace(/\s+/g,' ').trim().slice(0,320),reason:String(x?.reason||'').replace(/\s+/g,' ').trim().slice(0,240)};}
async function enrichCatalog(){if(!process.env.DEEPSEEK_API_KEY){console.log('[enrich] DeepSeek not configured; heuristic quality gate active');return;}const {rows}=await pool.query(`SELECT i.id,i.youtube_video_id,i.title,i.description,i.topic,c.name channel FROM learning_items i JOIN channels c ON c.id=i.channel_id WHERE i.source='youtube_feed' AND i.youtube_video_id IS NOT NULL AND i.enriched_at IS NULL ORDER BY i.published_at DESC NULLS LAST LIMIT 360`);if(!rows.length){console.log('[enrich] catalog already enriched');return;}let done=0,filtered=0;for(let n=0;n<rows.length;n+=8){const batch=rows.slice(n,n+8),result=await deepSeekBatch(batch.map(v=>({id:v.youtube_video_id,title:v.title,description:v.description,channel:v.channel,topic:v.topic})));const mapped=new Map((result?.videos||[]).map(v=>[String(v.id),v]));for(const v of batch){const raw=mapped.get(String(v.youtube_video_id));if(!raw)continue;const e=normalizeAi(raw);if(!e.recommendable)filtered++;await pool.query(`UPDATE learning_items SET quality_score=$2,recommendable=$3,content_type=$4,difficulty=$5,ai_summary=$6,ai_reason=$7,tags=$8::jsonb,enriched_at=NOW(),description=CASE WHEN $6<>'' THEN $6 ELSE description END WHERE id=$1`,[v.id,e.score,e.recommendable,e.type,e.difficulty,e.summary,e.reason,JSON.stringify(e.tags)]);done++;}if(n+8<rows.length)await timeout(120);}console.log(`[enrich] AI scored ${done}/${rows.length} videos; filtered ${filtered}`);}
async function refresh(){try{await catalog();await enrichCatalog();}catch(e){console.warn(`[catalog] refresh failed: ${e.message}`);}}
await catalog().catch(e=>console.warn(`[catalog] startup sync skipped: ${e.message}`));
await import('./server4.js');
enrichCatalog().catch(e=>console.warn(`[enrich] startup enrichment failed: ${e.message}`));
setInterval(()=>refresh(),12*3600000).unref();
