import pg from 'pg';
const {Pool}=pg;
const pool=new Pool({connectionString:process.env.DATABASE_URL,max:3,connectionTimeoutMillis:10000,idleTimeoutMillis:30000});
const timeout=ms=>new Promise(r=>setTimeout(r,ms));
function decode(s=''){return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');}
async function text(url,ms=7000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'Mozilla/5.0 RabbitHole/2.1'}});if(!r.ok)throw new Error(`${r.status}`);return await r.text();}finally{clearTimeout(t);}}
function heuristic(title=''){const t=title.toLowerCase();let score=70,type='explainer';if(/#shorts\b|\bshorts\b/.test(t)){score=10;type='short';}else if(/\b(trailer|teaser|giveaway|merch|channel update|announcement)\b/.test(t)){score=25;type='promo';}else if(/\b(livestream|live stream|stream highlights?)\b/.test(t)){score=35;type='livestream';}else if(/\b(podcast|interview|conversation)\b/.test(t)){score=64;type='interview';}else if(/\b(news|update|this week|today)\b/.test(t)){score=66;type='news';}if(/\b(how|why|explained|inside|history|science|engineering|future|economics|physics|math|system|works?)\b/.test(t))score+=8;if(t.length>45)score+=3;score=Math.max(0,Math.min(100,score));return{score,type,recommendable:score>=55};}
async function setup(){await pool.query(`
CREATE TABLE IF NOT EXISTS channel_ingestion(channel_id INT PRIMARY KEY REFERENCES channels(id) ON DELETE CASCADE,youtube_channel_id TEXT,last_synced_at TIMESTAMPTZ,last_error TEXT);
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'curated';
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS youtube_video_id TEXT;
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ;
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS recommendable BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS quality_score SMALLINT NOT NULL DEFAULT 70;
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS content_type TEXT;
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS ai_summary TEXT;
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS ai_reason TEXT;
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS difficulty SMALLINT;
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS tags JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS enriched_at TIMESTAMPTZ;
CREATE UNIQUE INDEX IF NOT EXISTS learning_items_youtube_video_id_uidx ON learning_items(youtube_video_id) WHERE youtube_video_id IS NOT NULL;
DELETE FROM daily_picks WHERE item_id IS NULL;
UPDATE learning_items SET recommendable=TRUE,quality_score=100,content_type=COALESCE(content_type,'curated'),enriched_at=COALESCE(enriched_at,NOW()) WHERE source='curated';
`);}
async function resolve(c){const cached=(await pool.query('SELECT youtube_channel_id FROM channel_ingestion WHERE channel_id=$1',[c.id])).rows[0]?.youtube_channel_id;if(cached)return cached;const html=await text(c.url);const id=[/"channelId":"(UC[\w-]{20,})"/,/"externalId":"(UC[\w-]{20,})"/,/youtube\.com\/channel\/(UC[\w-]{20,})/].map(x=>html.match(x)?.[1]).find(Boolean);if(!id)throw new Error('channel id not found');await pool.query(`INSERT INTO channel_ingestion(channel_id,youtube_channel_id) VALUES($1,$2) ON CONFLICT(channel_id) DO UPDATE SET youtube_channel_id=EXCLUDED.youtube_channel_id`,[c.id,id]);return id;}
function entries(xml){return(xml.match(/<entry>[\s\S]*?<\/entry>/g)||[]).map(b=>({id:b.match(/<yt:videoId>([^<]+)<\/yt:videoId>/)?.[1],title:decode(b.match(/<title>([\s\S]*?)<\/title>/)?.[1]||'').trim(),description:decode(b.match(/<media:description>([\s\S]*?)<\/media:description>/)?.[1]||'').replace(/\s+/g,' ').trim().slice(0,1200),published:b.match(/<published>([^<]+)<\/published>/)?.[1]||null})).filter(x=>x.id&&x.title).slice(0,12);}
async function sync(c){try{const yid=await resolve(c),xml=await text(`https://www.youtube.com/feeds/videos.xml?channel_id=${yid}`),vs=entries(xml);for(const v of vs){const h=heuristic(v.title);await pool.query(`INSERT INTO learning_items(track_id,channel_id,title,url,topic,description,item_order,repeat_after_days,source,youtube_video_id,published_at,recommendable,quality_score,content_type) VALUES(NULL,$1,$2,$3,$4,$5,NULL,60,'youtube_feed',$6,$7,$8,$9,$10) ON CONFLICT(url) DO UPDATE SET title=EXCLUDED.title,topic=EXCLUDED.topic,description=CASE WHEN learning_items.source='curated' THEN learning_items.description ELSE EXCLUDED.description END,source=CASE WHEN learning_items.source='curated' THEN 'curated' ELSE 'youtube_feed' END,youtube_video_id=COALESCE(learning_items.youtube_video_id,EXCLUDED.youtube_video_id),published_at=EXCLUDED.published_at,recommendable=CASE WHEN learning_items.source='curated' THEN TRUE WHEN learning_items.enriched_at IS NOT NULL THEN learning_items.recommendable ELSE EXCLUDED.recommendable END,quality_score=CASE WHEN learning_items.source='curated' THEN 100 WHEN learning_items.enriched_at IS NOT NULL THEN learning_items.quality_score ELSE EXCLUDED.quality_score END,content_type=CASE WHEN learning_items.source='curated' THEN COALESCE(learning_items.content_type,'curated') WHEN learning_items.enriched_at IS NOT NULL THEN learning_items.content_type ELSE EXCLUDED.content_type END`,[c.id,v.title,`https://www.youtube.com/watch?v=${v.id}`,c.topic,v.description||`Recent upload from ${c.name}.`,v.id,v.published,h.recommendable,h.score,h.type]);}await pool.query(`INSERT INTO channel_ingestion(channel_id,youtube_channel_id,last_synced_at,last_error) VALUES($1,$2,NOW(),NULL) ON CONFLICT(channel_id) DO UPDATE SET youtube_channel_id=EXCLUDED.youtube_channel_id,last_synced_at=NOW(),last_error=NULL`,[c.id,yid]);return vs.length;}catch(e){console.warn(`[catalog] ${c.name}: ${e.message}`);await pool.query(`INSERT INTO channel_ingestion(channel_id,last_synced_at,last_error) VALUES($1,NOW(),$2) ON CONFLICT(channel_id) DO UPDATE SET last_synced_at=NOW(),last_error=EXCLUDED.last_error`,[c.id,String(e.message).slice(0,250)]).catch(()=>{});return 0;}}
async function catalog(){await setup();const{rows}=await pool.query(`SELECT c.id,c.name,c.url,c.topic,ci.last_synced_at FROM channels c LEFT JOIN channel_ingestion ci ON ci.channel_id=c.id ORDER BY c.sort_order`);const stale=rows.filter(x=>!x.last_synced_at||Date.now()-new Date(x.last_synced_at).getTime()>12*3600000);let total=0;for(let i=0;i<stale.length;i+=6){const n=await Promise.all(stale.slice(i,i+6).map(sync));total+=n.reduce((a,b)=>a+b,0);if(i+6<stale.length)await timeout(150);}const count=+(await pool.query('SELECT COUNT(*)::int c FROM learning_items')).rows[0].c;console.log(`[catalog] synced ${stale.length} channels / ${total} feed entries; ${count} videos available`);}
try{await catalog();}catch(e){console.warn(`[catalog] startup sync skipped: ${e.message}`);}finally{await pool.end();}
await import('./server4.js');
