import express from 'express';
import pg from 'pg';
import path from 'path';
import { fileURLToPath } from 'url';

const { Pool } = pg;
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORT = Number(process.env.PORT || 3000);
const DEEPSEEK_MODEL = process.env.DEEPSEEK_MODEL || 'deepseek-flash';
const pool = new Pool({ connectionString: process.env.DATABASE_URL, max: 10, idleTimeoutMillis: 60000, connectionTimeoutMillis: 10000 });
const TOPICS = ['Future & AI','Science','Engineering','World & Systems','Money & Business','Documentaries'];
const META = {
  'Future & AI':['WHAT CHANGES NEXT','01'], Science:['MAKE REALITY WEIRDER','02'], Engineering:['HOW THINGS ACTUALLY WORK','03'],
  'World & Systems':['SEE THE MACHINERY','04'], 'Money & Business':['UNDERSTAND THE INCENTIVES','05'], Documentaries:['STORIES WORTH AN HOUR','06']
};
const TRACKS = [
  { slug:'3b1b-neural-networks-foundations', channel:'3Blue1Brown', title:'Neural Networks — Foundations', topic:'Science', items:[
    ['But what is a neural network? | Deep learning chapter 1','https://www.youtube.com/watch?v=aircAruvnKk','Neurons, layers, weights and the basic picture.'],
    ['Gradient descent, how neural networks learn | Deep learning chapter 2','https://www.youtube.com/watch?v=IHZwWFHWa-w','How the network actually learns from error.'],
    ['What is backpropagation really doing? | Deep learning chapter 3','https://www.youtube.com/watch?v=Ilg3gGewQ5U','The intuition behind propagating error backward.'],
    ['Backpropagation calculus | Deep learning chapter 4','https://www.youtube.com/watch?v=tIeHLnjs5U8','The calculus behind the intuition from chapter 3.']
  ]},
  { slug:'3b1b-linear-algebra-foundations', channel:'3Blue1Brown', title:'Essence of Linear Algebra — Foundations', topic:'Science', items:[
    ['Vectors, what even are they? | Essence of linear algebra, chapter 1','https://www.youtube.com/watch?v=fNk_zzaMoSs','Start with the visual meaning of vectors.'],
    ['Linear combinations, span, and basis vectors | Chapter 2','https://www.youtube.com/watch?v=k7RM-ot2NWY','Understand the space generated by vectors.'],
    ['Linear transformations and matrices | Chapter 3','https://www.youtube.com/watch?v=kYB8IZa5AuE','See matrices as transformations rather than grids of numbers.'],
    ['Matrix multiplication as composition | Chapter 4','https://www.youtube.com/watch?v=XkY2DOUCWMU','Why multiplying matrices means composing transformations.']
  ]}
];

async function initDb(){
  if(!process.env.DATABASE_URL) throw new Error('DATABASE_URL missing');
  await pool.query(`
    CREATE TABLE IF NOT EXISTS learning_tracks(id SERIAL PRIMARY KEY,slug TEXT UNIQUE NOT NULL,channel_id INT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,title TEXT NOT NULL,topic TEXT NOT NULL,strict_order BOOLEAN NOT NULL DEFAULT TRUE);
    CREATE TABLE IF NOT EXISTS learning_items(id SERIAL PRIMARY KEY,track_id INT REFERENCES learning_tracks(id) ON DELETE CASCADE,channel_id INT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,title TEXT NOT NULL,url TEXT UNIQUE NOT NULL,topic TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',item_order INT,repeat_after_days INT NOT NULL DEFAULT 45);
    CREATE TABLE IF NOT EXISTS item_prerequisites(item_id INT NOT NULL REFERENCES learning_items(id) ON DELETE CASCADE,prerequisite_item_id INT NOT NULL REFERENCES learning_items(id) ON DELETE CASCADE,PRIMARY KEY(item_id,prerequisite_item_id));
    CREATE TABLE IF NOT EXISTS item_progress(item_id INT PRIMARY KEY REFERENCES learning_items(id) ON DELETE CASCADE,status TEXT NOT NULL DEFAULT 'unseen' CHECK(status IN('unseen','in_progress','completed')),started_at TIMESTAMPTZ,last_opened_at TIMESTAMPTZ,completed_at TIMESTAMPTZ,completion_count INT NOT NULL DEFAULT 0,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS recommendation_history(id BIGSERIAL PRIMARY KEY,pick_date DATE NOT NULL,item_id INT REFERENCES learning_items(id) ON DELETE SET NULL,channel_id INT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,reason TEXT NOT NULL,recommended_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'curated';
    ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS youtube_video_id TEXT;
    ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ;
    ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS recommendable BOOLEAN NOT NULL DEFAULT TRUE;
    ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS quality_score SMALLINT NOT NULL DEFAULT 70;
    ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS content_type TEXT;
    ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS ai_summary TEXT;
    ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS ai_reason TEXT;
    ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS difficulty SMALLINT;
    ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS tags JSONB NOT NULL DEFAULT '[]'::jsonb;
    ALTER TABLE learning_items ADD COLUMN IF NOT EXISTS enriched_at TIMESTAMPTZ;
    ALTER TABLE daily_picks ADD COLUMN IF NOT EXISTS item_id INT REFERENCES learning_items(id) ON DELETE SET NULL;
    ALTER TABLE daily_picks ADD COLUMN IF NOT EXISTS reason TEXT;
    ALTER TABLE daily_picks ADD COLUMN IF NOT EXISTS ai_why TEXT;
  `);
  for(const t of TRACKS){
    const c=(await pool.query('SELECT id FROM channels WHERE name=$1',[t.channel])).rows[0]; if(!c) continue;
    const tr=(await pool.query(`INSERT INTO learning_tracks(slug,channel_id,title,topic) VALUES($1,$2,$3,$4) ON CONFLICT(slug) DO UPDATE SET channel_id=EXCLUDED.channel_id,title=EXCLUDED.title,topic=EXCLUDED.topic RETURNING id`,[t.slug,c.id,t.title,t.topic])).rows[0];
    let prev=null;
    for(let n=0;n<t.items.length;n++){
      const [title,url,description]=t.items[n];
      const it=(await pool.query(`INSERT INTO learning_items(track_id,channel_id,title,url,topic,description,item_order,source,recommendable,quality_score,content_type,enriched_at) VALUES($1,$2,$3,$4,$5,$6,$7,'curated',TRUE,100,'curated',NOW()) ON CONFLICT(url) DO UPDATE SET track_id=EXCLUDED.track_id,channel_id=EXCLUDED.channel_id,title=EXCLUDED.title,topic=EXCLUDED.topic,description=EXCLUDED.description,item_order=EXCLUDED.item_order,source='curated',recommendable=TRUE,quality_score=100,content_type='curated',enriched_at=NOW() RETURNING id`,[tr.id,c.id,title,url,t.topic,description,n+1])).rows[0];
      if(prev) await pool.query('INSERT INTO item_prerequisites(item_id,prerequisite_item_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[it.id,prev]);
      prev=it.id;
    }
  }
}

function cleanWhy(value){
  if(typeof value!=='string') return null;
  const compact=value.replace(/\s+/g,' ').trim();
  return compact?compact.slice(0,240):null;
}
async function deepSeekJSON(systemPrompt,userPayload,{timeoutMs=6000}={}){
  if(!process.env.DEEPSEEK_API_KEY) return null;
  const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),timeoutMs);
  try{
    const response=await fetch('https://api.deepseek.com/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${process.env.DEEPSEEK_API_KEY}`},body:JSON.stringify({model:DEEPSEEK_MODEL,temperature:0.2,max_tokens:350,response_format:{type:'json_object'},messages:[{role:'system',content:systemPrompt},{role:'user',content:JSON.stringify(userPayload)}]}),signal:controller.signal});
    if(!response.ok){console.warn(`DeepSeek HTTP ${response.status}`);return null;}
    const data=await response.json(),text=data?.choices?.[0]?.message?.content; return text?JSON.parse(text):null;
  }catch(error){console.warn(`DeepSeek fallback: ${error.name||'error'}`);return null;} finally{clearTimeout(timer);}
}
async function recentTaste(){
  const {rows}=await pool.query(`SELECT h.reason,c.name AS channel,c.topic,i.title AS item_title,COALESCE(p.status,'unseen') AS status FROM recommendation_history h JOIN channels c ON c.id=h.channel_id LEFT JOIN learning_items i ON i.id=h.item_id LEFT JOIN item_progress p ON p.item_id=h.item_id ORDER BY h.recommended_at DESC LIMIT 12`);
  return rows.map(r=>({channel:r.channel,topic:r.topic,title:r.item_title||null,status:r.status,reason:r.reason}));
}
async function aiPickLearningCandidate(candidates){
  if(!process.env.DEEPSEEK_API_KEY||candidates.length<2) return null;
  const history=await recentTaste();
  const result=await deepSeekJSON(`You are the final ranking layer for a nightly learning app. Every candidate already passed hard prerequisite, sequence, cooldown and quality gates. Choose only a supplied id. Prefer intellectual value, novelty, strong explanatory depth, and a useful change of pace given recent history. Use qualityScore as a signal, not an absolute rule. Return JSON exactly like {"id":123,"why":"one concise sentence explaining why this fits tonight"}.`,{history,candidates});
  const id=Number(result?.id); if(!candidates.some(c=>c.id===id)) return null; return {id,why:cleanWhy(result?.why)};
}

const channel=r=>({id:+r.id,name:r.name,handle:r.handle,url:r.channel_url||r.url,topic:r.channel_topic||r.topic,description:r.channel_description||r.description,vibe:r.vibe,hook:+r.hook});
const item=r=>r.item_id?{id:+r.item_id,title:r.item_title,url:r.item_url,description:r.ai_summary||r.item_description||'',order:r.item_order==null?null:+r.item_order,series:r.track_title||null,seriesSize:r.track_size==null?null:+r.track_size,status:r.progress_status||'unseen',qualityScore:r.quality_score==null?null:+r.quality_score,contentType:r.content_type||null,difficulty:r.difficulty==null?null:+r.difficulty}:null;
const PICK=`SELECT d.pick_date,d.topic AS pick_topic,d.reason,d.ai_why,c.id,c.name,c.handle,c.url AS channel_url,c.topic AS channel_topic,c.description AS channel_description,c.vibe,c.hook,i.id AS item_id,i.title AS item_title,i.url AS item_url,i.description AS item_description,i.ai_summary,i.quality_score,i.content_type,i.difficulty,i.item_order,t.title AS track_title,(SELECT COUNT(*) FROM learning_items x WHERE x.track_id=t.id) AS track_size,COALESCE(p.status,'unseen') AS progress_status FROM daily_picks d JOIN channels c ON c.id=d.channel_id LEFT JOIN learning_items i ON i.id=d.item_id LEFT JOIN learning_tracks t ON t.id=i.track_id LEFT JOIN item_progress p ON p.item_id=i.id`;
const pack=r=>({date:r.pick_date,topic:r.pick_topic,reason:r.reason||'NEW RABBIT HOLE',aiWhy:r.ai_why||null,channel:channel(r),item:item(r)});
async function today(date){const r=(await pool.query(`${PICK} WHERE d.pick_date=$1`,[date])).rows[0];return r?pack(r):null;}
async function unmet(id){const r=(await pool.query(`WITH RECURSIVE d AS(SELECT prerequisite_item_id id,1 depth FROM item_prerequisites WHERE item_id=$1 UNION ALL SELECT p.prerequisite_item_id,d.depth+1 FROM d JOIN item_prerequisites p ON p.item_id=d.id) SELECT d.id FROM d LEFT JOIN item_progress x ON x.item_id=d.id WHERE COALESCE(x.status,'unseen')<>'completed' ORDER BY depth DESC LIMIT 1`,[id])).rows[0];return r?+r.id:null;}

async function learningChoice(topic='',exclude=null){
  const q=[topic||null,exclude||null];
  let r=(await pool.query(`SELECT i.id FROM item_progress p JOIN learning_items i ON i.id=p.item_id WHERE p.status='in_progress' AND ($1::text IS NULL OR i.topic=$1) AND ($2::int IS NULL OR i.id<>$2) ORDER BY p.last_opened_at DESC NULLS LAST,p.updated_at DESC LIMIT 1`,q)).rows[0];
  if(r) return {id:+r.id,reason:'CONTINUE WHERE YOU LEFT OFF',aiWhy:null};
  r=(await pool.query(`WITH a AS(SELECT DISTINCT i.track_id FROM item_progress p JOIN learning_items i ON i.id=p.item_id WHERE i.track_id IS NOT NULL AND p.status IN('in_progress','completed')) SELECT i.id FROM learning_items i JOIN a ON a.track_id=i.track_id LEFT JOIN item_progress p ON p.item_id=i.id WHERE COALESCE(p.status,'unseen')<>'completed' AND ($1::text IS NULL OR i.topic=$1) AND ($2::int IS NULL OR i.id<>$2) ORDER BY i.item_order LIMIT 1`,q)).rows[0];
  if(r){const pre=await unmet(+r.id);return {id:pre||+r.id,reason:pre?'PREREQUISITE FIRST':'NEXT IN SERIES',aiWhy:null};}
  const rows=(await pool.query(`SELECT i.id,i.title,COALESCE(i.ai_summary,i.description) description,i.topic,i.item_order,i.quality_score,i.content_type,i.difficulty,c.name AS channel,t.title AS series FROM learning_items i JOIN channels c ON c.id=i.channel_id LEFT JOIN learning_tracks t ON t.id=i.track_id LEFT JOIN item_progress p ON p.item_id=i.id WHERE COALESCE(p.status,'unseen')='unseen' AND i.recommendable=TRUE AND ($1::text IS NULL OR i.topic=$1) AND ($2::int IS NULL OR i.id<>$2) AND NOT EXISTS(SELECT 1 FROM recommendation_history h WHERE h.item_id=i.id AND h.recommended_at>NOW()-INTERVAL '14 days') ORDER BY (i.quality_score + random()*12) DESC,i.published_at DESC NULLS LAST LIMIT 18`,q)).rows;
  const eligible=[];
  for(const x of rows){
    const pre=await unmet(+x.id); if(pre===exclude) continue;
    if(pre){
      const p=(await pool.query(`SELECT i.id,i.title,COALESCE(i.ai_summary,i.description) description,i.topic,i.item_order,i.quality_score,i.content_type,i.difficulty,c.name AS channel,t.title AS series FROM learning_items i JOIN channels c ON c.id=i.channel_id LEFT JOIN learning_tracks t ON t.id=i.track_id WHERE i.id=$1`,[pre])).rows[0];
      if(p&&!eligible.some(e=>e.id===+p.id)) eligible.push({...p,id:+p.id,forcedPrerequisite:true});
    }else eligible.push({...x,id:+x.id,forcedPrerequisite:false});
  }
  if(eligible.length){
    const forced=eligible.filter(x=>x.forcedPrerequisite),poolToRank=forced.length?forced:eligible;
    const ai=await aiPickLearningCandidate(poolToRank.map(x=>({id:x.id,title:x.title,channel:x.channel,topic:x.topic,series:x.series||null,order:x.item_order==null?null:+x.item_order,description:x.description,qualityScore:+x.quality_score||70,contentType:x.content_type||null,difficulty:x.difficulty==null?null:+x.difficulty})));
    const chosenId=ai?.id||poolToRank[0].id; return {id:chosenId,reason:forced.length?'PREREQUISITE FIRST':'NEW RABBIT HOLE',aiWhy:ai?.why||null};
  }
  r=(await pool.query(`SELECT i.id FROM learning_items i JOIN item_progress p ON p.item_id=i.id WHERE p.status='completed' AND i.recommendable=TRUE AND ($1::text IS NULL OR i.topic=$1) AND ($2::int IS NULL OR i.id<>$2) AND p.completed_at<=NOW()-(i.repeat_after_days*INTERVAL '1 day') ORDER BY i.quality_score DESC,p.completed_at LIMIT 1`,q)).rows[0];
  return r?{id:+r.id,reason:'WORTH REVISITING',aiWhy:null}:null;
}
async function fallbackVideo(topic='',exclude=null){
  const rows=(await pool.query(`SELECT i.id FROM learning_items i WHERE i.recommendable=TRUE AND ($1::text IS NULL OR i.topic=$1) AND ($2::int IS NULL OR i.id<>$2) ORDER BY i.quality_score DESC,i.published_at DESC NULLS LAST,random() LIMIT 16`,[topic||null,exclude||null])).rows;
  for(const x of rows){const pre=await unmet(+x.id);if(pre===exclude)continue;return {id:pre||+x.id,reason:pre?'PREREQUISITE FIRST':'CURATED FALLBACK',aiWhy:null};}
  return null;
}
async function save(date,topic,channelId,itemId,reason,aiWhy=null){
  await pool.query(`INSERT INTO daily_picks(pick_date,topic,channel_id,item_id,reason,ai_why) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(pick_date) DO UPDATE SET topic=EXCLUDED.topic,channel_id=EXCLUDED.channel_id,item_id=EXCLUDED.item_id,reason=EXCLUDED.reason,ai_why=EXCLUDED.ai_why,updated_at=NOW()`,[date,topic,channelId,itemId,reason,aiWhy]);
  await pool.query('INSERT INTO recommendation_history(pick_date,item_id,channel_id,reason) VALUES($1,$2,$3,$4)',[date,itemId,channelId,reason]);
  return today(date);
}

const app=express(); app.use(express.json({limit:'32kb'}));
app.get('/api/health',async(_q,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,database:'connected',ai:process.env.DEEPSEEK_API_KEY?'configured':'disabled',aiModel:process.env.DEEPSEEK_API_KEY?DEEPSEEK_MODEL:null});}catch(e){res.status(503).json({ok:false,error:e.message});}});
app.get('/api/ai/status',(_q,res)=>res.json({configured:Boolean(process.env.DEEPSEEK_API_KEY),model:process.env.DEEPSEEK_API_KEY?DEEPSEEK_MODEL:null,role:'catalog-enrichment-and-reranking',hardRules:['resume unfinished','series order','prerequisites','cooldowns','quality gate']}));
app.get('/api/catalog/status',async(_q,res)=>{try{const r=(await pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE recommendable)::int recommendable,COUNT(*) FILTER(WHERE source='youtube_feed')::int feed,COUNT(*) FILTER(WHERE source='youtube_feed' AND enriched_at IS NOT NULL)::int ai_enriched,COUNT(*) FILTER(WHERE source='youtube_feed' AND recommendable=FALSE)::int filtered,ROUND(AVG(quality_score))::int avg_score FROM learning_items`)).rows[0];res.json(r);}catch(e){res.status(500).json({error:'Could not load catalog status.'});}});
app.get('/api/topics',async(_q,res)=>{try{const rows=(await pool.query('SELECT topic,COUNT(*)::int count FROM channels GROUP BY topic ORDER BY MIN(sort_order)')).rows;res.json(rows.map(r=>({...r,kicker:META[r.topic]?.[0]||'',glyph:META[r.topic]?.[1]||''})));}catch{res.status(500).json({error:'Could not load topics.'});}});
app.get('/api/channels',async(req,res)=>{try{const t=typeof req.query.topic==='string'?req.query.topic:'';const rows=t?(await pool.query('SELECT * FROM channels WHERE topic=$1 ORDER BY sort_order',[t])).rows:(await pool.query('SELECT * FROM channels ORDER BY sort_order')).rows;res.json(rows.map(channel));}catch{res.status(500).json({error:'Could not load channels.'});}});
app.get('/api/today',async(req,res)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(req.query.date||''))return res.status(400).json({error:'Use date=YYYY-MM-DD.'});try{res.json(await today(req.query.date));}catch(e){res.status(500).json({error:'Could not load today’s pick.'});}});
app.get('/api/progress',async(_q,res)=>{try{const active=(await pool.query(`SELECT t.id,t.title,t.topic,c.name channel,COUNT(i.id)::int total,COUNT(*) FILTER(WHERE p.status='completed')::int completed FROM learning_tracks t JOIN channels c ON c.id=t.channel_id JOIN learning_items i ON i.track_id=t.id LEFT JOIN item_progress p ON p.item_id=i.id GROUP BY t.id,c.name HAVING COUNT(*) FILTER(WHERE p.status IN('in_progress','completed'))>0 AND COUNT(*) FILTER(WHERE p.status='completed')<COUNT(i.id) ORDER BY MAX(p.updated_at) DESC NULLS LAST`)).rows;const completed=+(await pool.query("SELECT COUNT(*)::int count FROM item_progress WHERE status='completed'")).rows[0].count;res.json({active,completed});}catch{res.status(500).json({error:'Could not load progress.'});}});
app.post('/api/items/:id/start',async(req,res)=>{try{await pool.query(`INSERT INTO item_progress(item_id,status,started_at,last_opened_at) VALUES($1,'in_progress',NOW(),NOW()) ON CONFLICT(item_id) DO UPDATE SET status=CASE WHEN item_progress.status='completed' THEN 'completed' ELSE 'in_progress' END,started_at=COALESCE(item_progress.started_at,NOW()),last_opened_at=NOW(),updated_at=NOW()`,[+req.params.id]);res.json({ok:true});}catch{res.status(500).json({error:'Could not save progress.'});}});
app.post('/api/items/:id/complete',async(req,res)=>{try{await pool.query(`INSERT INTO item_progress(item_id,status,started_at,last_opened_at,completed_at,completion_count) VALUES($1,'completed',NOW(),NOW(),NOW(),1) ON CONFLICT(item_id) DO UPDATE SET status='completed',started_at=COALESCE(item_progress.started_at,NOW()),last_opened_at=NOW(),completed_at=NOW(),completion_count=item_progress.completion_count+1,updated_at=NOW()`,[+req.params.id]);res.json({ok:true});}catch{res.status(500).json({error:'Could not mark watched.'});}});
app.post('/api/pick',async(req,res)=>{const date=String(req.body?.date||''),requested=typeof req.body?.topic==='string'?req.body.topic:'',reroll=!!req.body?.reroll;if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return res.status(400).json({error:'Use date=YYYY-MM-DD.'});if(requested&&!TOPICS.includes(requested))return res.status(400).json({error:'Unknown topic.'});try{const existing=await today(date);if(existing&&!reroll)return res.json(existing);let choice=await learningChoice(requested,reroll?existing?.item?.id:null);if(!choice)choice=await fallbackVideo(requested,reroll?existing?.item?.id:null);if(!choice)return res.status(404).json({error:'No high-quality video candidates are available for this lane yet.'});const x=(await pool.query('SELECT i.id,i.channel_id,i.topic FROM learning_items i WHERE i.id=$1',[choice.id])).rows[0];res.json(await save(date,x.topic,+x.channel_id,+x.id,choice.reason,choice.aiWhy));}catch(e){console.error(e);res.status(500).json({error:'Could not choose tonight’s rabbit hole.'});}});
app.use(express.static(path.join(__dirname,'public'),{extensions:['html']})); app.use((_q,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
initDb().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log(`Rabbit Hole listening on :${PORT}; AI ${process.env.DEEPSEEK_API_KEY?'configured':'disabled'}; quality gate enabled`))).catch(e=>{console.error(e);process.exit(1);});
